blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/jaylouisw/HA/discussions
    about: Ask questions or discuss ideas
  - name: ðŸ“– Documentation
    url: https://github.com/jaylouisw/HA/tree/main/HAIMish
    about: Read the HAIMish documentation
